# -----------------------------------------------------
# Configuration file for your bot
# Copy this file to config.yml and update the values.
# -----------------------------------------------------

#-------------------------------------------------------
# Discord settings
# ------------------------------------------------------

# Your bot's authentication token, provided by Discord
token: "your-bot-token"

# Your bot's application's ID
appId: "your-app-id"

# Your Discord server's ID
guildId: "your-guild-id"

# -------------------------------------------------------
# AWS settings
# -------------------------------------------------------

# Your IAM user's access key ID
accessKeyId: "your-access-key-id"

# Your IAM user's secret access key
accessKeySecret: "your-secret-access-key"

# Your AWS region
region: "your-aws-region"

# -----------------------------------------------------------------------------------
# Your EC2 instances, defined by a friendly key and the instance information.
# You can also define AWS accessKeyId, accessKeySecret, and region for each instance.
# If you define them here, they will override those defined at the root level.
# -----------------------------------------------------------------------------------

instances:
#    # The name you will use in the start command
#    instanceKey:
#
#      # The ID for the EC2 instance
#      id:
#
#      # Keys to instances which must be running before this instance
#      depend: [otherInstance, someOtherInstance]
#
#      # The access key ID for the IAM user, if overriding the default
#      accessKeyId:
#
#      # The secret access key for the IAM user, if overriding the default
#      accessKeySecret:
#
#      # The region for this instance, if overriding the default
#      region:
  instance1:
    id: "your-instance-id"
